from colorama import Fore, Style

FB = f'{Fore.BLACK}'
FBLU = f'{Fore.BLUE}'
FC = f'{Fore.CYAN}'
FG = f'{Fore.GREEN}'
FM = f'{Fore.MAGENTA}'
FR = f'{Fore.RED}'
FW = f'{Fore.WHITE}'
FY = f'{Fore.YELLOW}'

FLB = f'{Fore.LIGHTBLACK_EX}'
FLBLU = f'{Fore.LIGHTBLUE_EX}'
FLC = f'{Fore.LIGHTCYAN_EX}'
FLG = f'{Fore.LIGHTGREEN_EX}'
FLM = f'{Fore.LIGHTMAGENTA_EX}'
FLR = f'{Fore.LIGHTRED_EX}'
FLW = f'{Fore.LIGHTWHITE_EX}'
FLY = f'{Fore.LIGHTYELLOW_EX}'

BB = f'{Style.BRIGHT}{FB}'
BBLU = f'{Style.BRIGHT}{FBLU}'
BC = f'{Style.BRIGHT}{FC}'
BG = f'{Style.BRIGHT}{FG}'
BM = f'{Style.BRIGHT}{FM}'
BR = f'{Style.BRIGHT}{FR}'
BW = f'{Style.BRIGHT}{FW}'
BY = f'{Style.BRIGHT}{FY}'

BLB = f'{Style.BRIGHT}{FLB}'
BLC = f'{Style.BRIGHT}{FLC}'
BLG = f'{Style.BRIGHT}{FLG}'
BLM = f'{Style.BRIGHT}{FLM}'
BLR = f'{Style.BRIGHT}{FLR}'
BLW = f'{Style.BRIGHT}{FLW}'
BLY = f'{Style.BRIGHT}{FLY}'
BMLBLU = f'{Style.BRIGHT}{FLBLU}'

RS = f'{Fore.RESET}{Style.RESET_ALL}'